name: easy_fuel_2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_bloc: ^8.0.1
  authentication_module: ^0.0.1
  equatable: ^2.0.3
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.6
  shared_preferences: ^2.0.12
  flutterfire_cli: ^0.1.1+2
  flutterfire_ui: ^0.3.2
  google_sign_in: ^5.2.3
  flutter_advanced_drawer: ^1.3.0
  introduction_screen: ^3.0.0
  flutter_switch: ^0.3.2
  persistent_bottom_nav_bar: ^4.0.2
  geolocator: ^8.2.0
  location: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/

