// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbwbr4saVTd9p8Hgxzq4Do_AM0uu-1G1w',
    appId: '1:715465582044:android:191c930059d0761a169b19',
    messagingSenderId: '715465582044',
    projectId: 'easy-fuel-e9d2f',
    storageBucket: 'easy-fuel-e9d2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeWHPttB5eAPLM7AoaGEsWMOrKL8-rvSg',
    appId: '1:715465582044:ios:2478a00c70727ecb169b19',
    messagingSenderId: '715465582044',
    projectId: 'easy-fuel-e9d2f',
    storageBucket: 'easy-fuel-e9d2f.appspot.com',
    iosClientId: '715465582044-menfv86lgpbc0bfviul7asn1lhau107k.apps.googleusercontent.com',
    iosBundleId: 'com.example.iosapp',
  );
}
